apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: load-tester
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: loadtester
  chart:
    git: https://github.com/weaveworks/flagger
    ref: main
    path: charts/loadtester
  values:
    fullnameOverride: load-tester
